import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App.jsx";
import "./index.css";
import CustomApp from "./CustomApp.jsx";
import Users, { UsersWithImages } from "./Users.jsx";
import ShapeContainer from "./ShapeContainer.jsx";
import Chameleon from "./Chameleon.jsx";
import Friends from "./Friends.jsx";
import Container from "./page/Container.jsx";
ReactDOM.createRoot(document.getElementById("root")).render(<Container />);
